variables:
  HADOOP_PROTOC_PATH: /usr/bin/protoc-2

stages:
  - compile
  - pretest
  - test

pretest:
  stage: pretest
  tags:
    - k8s
    - hadoop2
  script:
    -  ./submodule-ci.sh
  artifacts:
    paths:
      - submodule-ci.yml

submodule-test:
  stage: test
  trigger:
    strategy: depend
    include:
      - artifact: submodule-ci.yml
        job: pretest


compile:
  stage: compile
  tags:
    - k8s
    - hadoop2
  script:
    - mvn clean install package -DskipTests
